export const moviesList = [
  {
    id: 1,
    title: "Demon Slayer: Kimetsu no Yaiba – The Movie: Infinity Castle",
    year: 2025,
    description:
      "Tanjiro Kamado and the Demon Slayer Corps face Muzan Kibutsuji in a climactic battle within the Infinity Castle.",
    duration: "2h 35m",
    releaseDate: "2025-09-12",
    director: "Haruo Sotozaki",
    producer: "Akifumi Fujio, Masanori Miyake, Yūma Takahashi",
    cast: [
      "Natsuki Hanae",
      "Akari Kitō",
      "Yoshitsugu Matsuoka",
      "Hiro Shimono",
      "Takahiro Sakurai",
      "Akira Ishida",
    ],
    poster:" https://m.media-amazon.com/images/M/MV5BMWU1OGEwNmQtNGM3MS00YTYyLThmYmMtN2FjYzQzNzNmNTE0XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    rating: "8.6/10",
    trailer: "https://www.youtube.com/watch?v=x7uLutVRBfI",
  },
  {
    id: 2,
    title: "The Dark Knight",
    year: 2008,
    description:
      "Batman faces his greatest psychological and physical tests when the Joker unleashes chaos on Gotham.",
    duration: "2h 32m",
    releaseDate: "2008-07-18",
    director: "Christopher Nolan",
    producer: "Emma Thomas",
    cast: ["Christian Bale", "Heath Ledger", "Aaron Eckhart", "Michael Caine"],
    poster: "https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
    rating: "9.0/10",
    trailer: "https://www.youtube.com/watch?v=EXeTwQWrcwY",
  },
  {
    id: 3,
    title: "Inception",
    year: 2010,
    description:
      "Dom Cobb, a skilled thief, steals secrets from deep within the subconscious during the dream state.",
    duration: "2h 28m",
    releaseDate: "2010-07-16",
    director: "Christopher Nolan",
    producer: "Emma Thomas",
    cast: [
      "Leonardo DiCaprio",
      "Joseph Gordon-Levitt",
      "Elliot Page",
      "Tom Hardy",
    ],
    poster: "https://image.tmdb.org/t/p/w500/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg",
    rating: "8.8/10",
    trailer: "https://www.youtube.com/watch?v=YoHD9XEInc0",
  },
  {
    id: 4,
    title: "The Matrix",
    year: 1999,
    description:
      "A computer hacker learns about the true nature of his reality and his role in the war against its controllers.",
    duration: "2h 16m",
    releaseDate: "1999-03-31",
    director: "The Wachowskis",
    producer: "Joel Silver",
    cast: [
      "Keanu Reeves",
      "Laurence Fishburne",
      "Carrie-Anne Moss",
      "Hugo Weaving",
    ],
    poster: "https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg",
    rating: "8.7/10",
    trailer: "https://www.youtube.com/watch?v=vKQi3bBA1y8",
  },
  {
    id: 5,
    title: "Avatar",
    year: 2009,
    description:
      "On the lush alien world of Pandora, a paraplegic Marine becomes torn between following orders and protecting the world he feels is his home.",
    duration: "2h 42m",
    releaseDate: "2009-12-18",
    director: "James Cameron",
    producer: "James Cameron",
    cast: [
      "Sam Worthington",
      "Zoe Saldaña",
      "Sigourney Weaver",
      "Stephen Lang",
    ],
    poster: "https://image.tmdb.org/t/p/w500/jRXYjXNq0Cs2TcJjLkki24MLp7u.jpg",
    rating: "7.9/10",
    trailer: "https://www.youtube.com/watch?v=5PSNL1qE6VY",
  },
  {
    id: 6,
    title: "Gladiator",
    year: 2000,
    description:
      "A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery.",
    duration: "2h 35m",
    releaseDate: "2000-05-05",
    director: "Ridley Scott",
    producer: "Douglas Wick",
    cast: ["Russell Crowe", "Joaquin Phoenix", "Connie Nielsen", "Oliver Reed"],
    poster: "https://image.tmdb.org/t/p/w500/ty8TGRuvJLPUmAR1H1nRIsgwvim.jpg",
    rating: "8.5/10",
    trailer: "https://www.youtube.com/watch?v=P5ieIbInFpg",
  },
  {
    id: 7,
    title: "Parasite",
    year: 2019,
    description:
      "A poor family schemes to become employed by a wealthy household by infiltrating their lives and posing as unrelated, highly qualified individuals.",
    duration: "2h 12m",
    releaseDate: "2019-05-30",
    director: "Bong Joon-ho",
    producer: "Kwak Sin-ae",
    cast: ["Song Kang-ho", "Lee Sun-kyun", "Cho Yeo-jeong", "Choi Woo-shik"],
    poster: "https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
    rating: "8.6/10",
    trailer: "https://www.youtube.com/watch?v=isOGD_7hNIY",
  },
  {
    id: 8,
    title: "Titanic",
    year: 1997,
    description:
      "A young couple from different social backgrounds fall in love aboard the ill-fated R.M.S. Titanic.",
    duration: "3h 14m",
    releaseDate: "1997-12-19",
    director: "James Cameron",
    producer: "James Cameron",
    cast: ["Leonardo DiCaprio", "Kate Winslet", "Billy Zane", "Kathy Bates"],
    poster: "https://image.tmdb.org/t/p/w500/9xjZS2rlVxm8SFx8kPC3aIGCOYQ.jpg",
    rating: "7.9/10",
    trailer: "https://www.youtube.com/watch?v=LuPB43YSgCs",
  },
  {
    id: 9,
    title: "The Shawshank Redemption",
    year: 1994,
    description:
      "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
    duration: "2h 22m",
    releaseDate: "1994-09-23",
    director: "Frank Darabont",
    producer: "Niki Marvin",
    cast: ["Tim Robbins", "Morgan Freeman", "Bob Gunton", "William Sadler"],
    poster: "https://image.tmdb.org/t/p/w500/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg",
    rating: "9.3/10",
    trailer: "https://www.youtube.com/watch?v=6hB3S9bIaco",
  },
  {
    id: 10,
    title: "Forrest Gump",
    year: 1994,
    description:
      "The presidencies of Kennedy and Johnson, the Vietnam War, and other history unfold through the perspective of an Alabama man with a low IQ.",
    duration: "2h 22m",
    releaseDate: "1994-07-06",
    director: "Robert Zemeckis",
    producer: "Wendy Finerman",
    cast: ["Tom Hanks", "Robin Wright", "Gary Sinise", "Sally Field"],
    poster: "https://image.tmdb.org/t/p/w500/saHP97rTPS5eLmrLQEcANmKrsFl.jpg",
    rating: "8.8/10",
    trailer: "https://www.youtube.com/watch?v=bLvqoHBptjg",
  },
  {
    id: 11,
    title: "Joker",
    year: 2019,
    description:
      "A mentally troubled comedian embarks on a downward spiral that leads to the creation of an iconic villain.",
    duration: "2h 2m",
    releaseDate: "2019-10-04",
    director: "Todd Phillips",
    producer: "Todd Phillips",
    cast: [
      "Joaquin Phoenix",
      "Robert De Niro",
      "Zazie Beetz",
      "Frances Conroy",
    ],
    poster: "https://image.tmdb.org/t/p/w500/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg",
    rating: "8.4/10",
    trailer: "https://www.youtube.com/watch?v=t433PEQGErc",
  },
  {
    id: 12,
    title: "Avengers: Endgame",
    year: 2019,
    description:
      "The Avengers assemble once more in order to reverse Thanos' actions and restore balance to the universe.",
    duration: "3h 1m",
    releaseDate: "2019-04-26",
    director: "Anthony Russo, Joe Russo",
    producer: "Kevin Feige",
    cast: [
      "Robert Downey Jr.",
      "Chris Evans",
      "Mark Ruffalo",
      "Chris Hemsworth",
    ],
    poster: "https://image.tmdb.org/t/p/w500/or06FN3Dka5tukK1e9sl16pB3iy.jpg",
    rating: "8.4/10",
    trailer: "https://www.youtube.com/watch?v=TcMBFSGVi1c",
  },
  {
    id: 13,
    title: "The Lion King",
    year: 1994,
    description:
      "A young lion prince flees his kingdom after the murder of his father, only to learn the true meaning of responsibility and bravery.",
    duration: "1h 28m",
    releaseDate: "1994-06-15",
    director: "Roger Allers, Rob Minkoff",
    producer: "Don Hahn",
    cast: [
      "Matthew Broderick",
      "Jeremy Irons",
      "James Earl Jones",
      "Moira Kelly",
    ],
    poster: "https://image.tmdb.org/t/p/w500/sKCr78MXSLixwmZ8DyJLrpMsd15.jpg",
    rating: "8.5/10",
    trailer: "https://www.youtube.com/watch?v=4sj1MT05lAA",
  },
  {
    id: 14,
    title: "The Godfather",
    year: 1972,
    description:
      "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.",
    duration: "2h 55m",
    releaseDate: "1972-03-24",
    director: "Francis Ford Coppola",
    producer: "Albert S. Ruddy",
    cast: ["Marlon Brando", "Al Pacino", "James Caan", "Robert Duvall"],
    poster: "https://image.tmdb.org/t/p/w500/3bhkrj58Vtu7enYsRolD1fZdja1.jpg",
    rating: "9.2/10",
    trailer: "https://www.youtube.com/watch?v=sY1S34973zA",
  },
  {
    id: 15,
    title: "Pulp Fiction",
    year: 1994,
    description:
      "The lives of two mob hitmen, a boxer, a gangster's wife, and a pair of diner bandits intertwine in four tales of violence and redemption.",
    duration: "2h 34m",
    releaseDate: "1994-10-14",
    director: "Quentin Tarantino",
    producer: "Lawrence Bender",
    cast: ["John Travolta", "Uma Thurman", "Samuel L. Jackson", "Bruce Willis"],
    poster: "https://image.tmdb.org/t/p/w500/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg",
    rating: "8.9/10",
    trailer: "https://www.youtube.com/watch?v=s7EdQ4FqbhY",
  },
  {
    id: 16,
    title: "Fight Club",
    year: 1999,
    description:
      "An insomniac office worker and a soap maker form an underground fight club that evolves into something far more.",
    duration: "2h 19m",
    releaseDate: "1999-10-15",
    director: "David Fincher",
    producer: "Art Linson",
    cast: ["Brad Pitt", "Edward Norton", "Helena Bonham Carter", "Meat Loaf"],
    poster: "https://image.tmdb.org/t/p/w500/bptfVGEQuv6vDTIMVCHjJ9Dz8PX.jpg",
    rating: "8.8/10",
    trailer: "https://www.youtube.com/watch?v=SUXWAEX2jlg",
  },
  {
    id: 17,
    title: "The Avengers",
    year: 2012,
    description:
      "Earth's mightiest heroes must come together to stop Loki and his alien army from enslaving humanity.",
    duration: "2h 23m",
    releaseDate: "2012-05-04",
    director: "Joss Whedon",
    producer: "Kevin Feige",
    cast: [
      "Robert Downey Jr.",
      "Chris Evans",
      "Scarlett Johansson",
      "Mark Ruffalo",
    ],
    poster: "https://image.tmdb.org/t/p/w500/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg",
    rating: "8.0/10",
    trailer: "https://www.youtube.com/watch?v=eOrNdBpGMv8",
  },
  {
    id: 18,
    title: "The Lord of the Rings: The Fellowship of the Ring",
    year: 2001,
    description:
      "A meek Hobbit and eight companions set out on a journey to destroy the One Ring and the Dark Lord Sauron.",
    duration: "2h 58m",
    releaseDate: "2001-12-19",
    director: "Peter Jackson",
    producer: "Peter Jackson",
    cast: ["Elijah Wood", "Ian McKellen", "Orlando Bloom", "Viggo Mortensen"],
    poster: "https://image.tmdb.org/t/p/w500/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg",
    rating: "8.8/10",
    trailer: "https://www.youtube.com/watch?v=V75dMMIW2B4",
  },
  {
    id: 19,
    title: "The Lord of the Rings: The Return of the King",
    year: 2003,
    description:
      "Gandalf and Aragorn lead the World of Men against Sauron's army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.",
    duration: "3h 21m",
    releaseDate: "2003-12-17",
    director: "Peter Jackson",
    producer: "Peter Jackson",
    cast: ["Elijah Wood", "Ian McKellen", "Viggo Mortensen", "Sean Astin"],
    poster: "https://image.tmdb.org/t/p/w500/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg",
    rating: "9.0/10",
    trailer: "https://www.youtube.com/watch?v=r5X-hFf6Bwo",
  },
  {
    id: 20,
    title: "The Lord of the Rings: The Two Towers",
    year: 2002,
    description:
      "While Frodo and Sam edge closer to Mordor with the help of Gollum, the divided fellowship makes a stand against Sauron's new ally, Saruman.",
    duration: "2h 59m",
    releaseDate: "2002-12-18",
    director: "Peter Jackson",
    producer: "Peter Jackson",
    cast: ["Elijah Wood", "Ian McKellen", "Viggo Mortensen", "Orlando Bloom"],
    poster: "https://image.tmdb.org/t/p/w500/5VTN0pR8gcqV3EPUHHfMGnJYN9L.jpg",
    rating: "8.9/10",
    trailer: "https://www.youtube.com/watch?v=LbfMDwc4azU",
  },
];